import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { apiErrorMessage, NetpayApiClient, netpayApi, newIdempotencyKey, type NetpayBranch, type NetpayCase, type NetpayClient, type NetpayCompany } from '../../api/netpay';

const states = ['received', 'triage', 'information_pending', 'ready', 'in_progress', 'submitted', 'blocked', 'completed', 'cancelled'];
const types = ['merchant_onboarding', 'branch_onboarding', 'tpv_activation', 'ecommerce_activation', 'bank_account_change', 'document_submission', 'legal_entity_change', 'franchisee_change', 'store_deactivation', 'terminal_replacement', 'support_incident', 'unclassified'];
const products = ['tpv', 'ecommerce', 'mixed', 'not_applicable'];
const priorities = ['urgent', 'high', 'normal', 'low'];

type Filters = { search: string; attention: string; state: string; type: string; product: string; assignee: string; client: string; branch: string; store: string };
type MasterNames = { client: string; company: string; branch: string; store: string };

function openAction(item: NetpayCase) { return item.next_actions.find((action) => action.status === 'open'); }
function lastActivity(item: NetpayCase) { return item.activities.at(-1); }
function isOverdue(item: NetpayCase) { const due = openAction(item)?.due_date; return Boolean(due && new Date(due) < new Date()); }
function label(value: string | null | undefined) { return value ? value.replaceAll('_', ' ') : '—'; }
function date(value: string | null | undefined) { return value ? new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium' }).format(new Date(value)) : 'Sin fecha'; }

export function NetpayInboxWorkspace({ client = netpayApi }: { client?: NetpayApiClient }) {
  const [items, setItems] = useState<NetpayCase[]>([]);
  const [names, setNames] = useState<Record<string, MasterNames>>({});
  const [filters, setFilters] = useState<Filters>({ search: '', attention: '', state: '', type: '', product: '', assignee: '', client: '', branch: '', store: '' });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [offset, setOffset] = useState(0);
  const [total, setTotal] = useState(0);
  const [creating, setCreating] = useState(false);
  const limit = 20;

  async function load() {
    setLoading(true); setError('');
    try {
      const query = [filters.search, filters.client, filters.branch, filters.store].filter(Boolean).join(' ');
      const page = await client.listInbox({ query, state: filters.state, product: filters.product, case_type_key: filters.type, responsible_principal_id: filters.assignee, requires_attention: filters.attention === '' ? undefined : filters.attention === 'yes', offset, limit });
      setItems(page.items); setTotal(page.total);
      const entries = await Promise.all(page.items.map(async (item) => {
        if (!item.branch_id) return [item.id, { client: item.client_id, company: item.company_id, branch: 'Sin sucursal', store: 'Sin Store ID' }] as const;
        try {
          const detail = await client.getMasterDetail(item.branch_id);
          const company = detail.companies.find((value) => value.id === item.company_id);
          const branch = company?.branches.find((value) => value.id === item.branch_id);
          return [item.id, { client: detail.display_name, company: company?.legal_name || item.company_id, branch: branch?.commercial_name || item.branch_id, store: branch?.store_reference?.store_id || 'Sin Store ID' }] as const;
        } catch { return [item.id, { client: item.client_id, company: item.company_id, branch: item.branch_id, store: item.store_reference_id || 'Sin Store ID' }] as const; }
      }));
      setNames(Object.fromEntries(entries));
    } catch (reason) { setError(apiErrorMessage(reason)); }
    finally { setLoading(false); }
  }

  useEffect(() => { void load(); }, [offset, filters.attention, filters.state, filters.type, filters.product, filters.assignee]);
  const visible = useMemo(() => items.filter((item) => {
    const master = names[item.id];
    const haystack = `${item.folio} ${item.original_description} ${master?.client || ''} ${master?.branch || ''} ${master?.store || ''}`.toLowerCase();
    return (!filters.search || haystack.includes(filters.search.toLowerCase())) && (!filters.client || master?.client.toLowerCase().includes(filters.client.toLowerCase())) && (!filters.branch || master?.branch.toLowerCase().includes(filters.branch.toLowerCase())) && (!filters.store || master?.store.toLowerCase().includes(filters.store.toLowerCase()));
  }), [items, names, filters.search, filters.client, filters.branch, filters.store]);
  const summary = { attention: items.filter((item) => item.requires_attention).length, overdue: items.filter(isOverdue).length, pending: items.filter((item) => item.state === 'information_pending').length, blocked: items.filter((item) => item.state === 'blocked').length, unassigned: items.filter((item) => !item.responsible_principal_id).length };

  return <section className="netpay-workspace">
    <header className="netpay-hero"><div><p className="eyebrow">OPERACIÓN ASISTIDA</p><h1>Netpay Inbox</h1><p>Casos tenant-owned para altas y servicio, con autoridad persistida.</p><small>Organización: {client.runtime.organizationLabel || client.runtime.organizationSelector}</small></div>{client.can('netpay.inbox.manage') && <button onClick={() => setCreating(true)}>Nueva solicitud</button>}</header>
    <section className="attention-summary" aria-label="Resumen de atención">
      <article className="attention"><b>{summary.attention}</b><span>Requieren atención</span></article><article><b>{summary.overdue}</b><span>Vencidos</span></article><article><b>{summary.pending}</b><span>Información pendiente</span></article><article><b>{summary.blocked}</b><span>Bloqueados</span></article><article><b>{summary.unassigned}</b><span>Sin asignar</span></article>
    </section>
    <form className="netpay-filters" aria-label="Filtros" onSubmit={(event) => { event.preventDefault(); setOffset(0); void load(); }}>
      <label>Buscar<input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Folio o descripción" /></label>
      <label>Atención<select value={filters.attention} onChange={(e) => setFilters({ ...filters, attention: e.target.value })}><option value="">Todas</option><option value="yes">Requiere atención</option><option value="no">Sin atención</option></select></label>
      <label>Estado<select value={filters.state} onChange={(e) => setFilters({ ...filters, state: e.target.value })}><option value="">Todos</option>{states.map((value) => <option key={value}>{value}</option>)}</select></label>
      <label>Tipo<select value={filters.type} onChange={(e) => setFilters({ ...filters, type: e.target.value })}><option value="">Todos</option>{types.map((value) => <option key={value}>{value}</option>)}</select></label>
      <label>Producto<select value={filters.product} onChange={(e) => setFilters({ ...filters, product: e.target.value })}><option value="">Todos</option>{products.map((value) => <option key={value}>{value}</option>)}</select></label>
      <label>Assignee<input value={filters.assignee} onChange={(e) => setFilters({ ...filters, assignee: e.target.value })} placeholder="Principal UUID" /></label>
      <label>Cliente<input value={filters.client} onChange={(e) => setFilters({ ...filters, client: e.target.value })} /></label><label>Sucursal<input value={filters.branch} onChange={(e) => setFilters({ ...filters, branch: e.target.value })} /></label><label>Store ID<input value={filters.store} onChange={(e) => setFilters({ ...filters, store: e.target.value })} /></label>
      <button type="submit">Aplicar</button>
    </form>
    {loading ? <p role="status">Cargando Netpay Inbox…</p> : error ? <div role="alert" className="error-panel"><p>{error}</p><button onClick={() => void load()}>Reintentar</button></div> : visible.length === 0 ? <div className="empty-state"><h2>Inbox vacío</h2><p>No hay casos para esta organización y filtros.</p></div> : <div className="netpay-table-wrap"><table><thead><tr><th>Atención</th><th>Caso</th><th>Jerarquía</th><th>Solicitud</th><th>Estado</th><th>Responsable</th><th>Siguiente acción</th><th>Actividad</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id} className={item.requires_attention ? 'needs-attention' : ''}><td>{item.requires_attention ? <strong>Requiere atención</strong> : 'Al día'}</td><td><Link to={`/netpay-inbox/${item.id}`}>{item.folio}</Link><small>{label(item.product)} · {label(item.priority)}</small></td><td>{names[item.id]?.client}<small>{names[item.id]?.company} → {names[item.id]?.branch} → {names[item.id]?.store}</small></td><td>{label(item.case_type_key)}<small>Objetivo: {item.expected_outcome || 'Pendiente'}</small></td><td>{label(item.state)}<small>Meta: {date(item.target_date)}</small></td><td>{item.responsible_principal_id || 'Sin asignar'}</td><td>{openAction(item)?.description || 'Sin siguiente acción'}<small>{isOverdue(item) ? 'Vencida' : date(openAction(item)?.due_date)}</small></td><td>{lastActivity(item)?.summary || 'Sin actividad'}<small>{date(lastActivity(item)?.created_at)}</small></td></tr>)}</tbody></table></div>}
    <footer className="pagination"><button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - limit))}>Anterior</button><span>{total === 0 ? 0 : offset + 1}–{Math.min(total, offset + limit)} de {total}</span><button disabled={offset + limit >= total} onClick={() => setOffset(offset + limit)}>Siguiente</button></footer>
    {creating && <CreateCaseFlow client={client} onClose={() => setCreating(false)} />}
  </section>;
}

function CreateCaseFlow({ client, onClose }: { client: NetpayApiClient; onClose: () => void }) {
  const navigate = useNavigate();
  const [step, setStep] = useState(1); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const [clientItem, setClientItem] = useState<NetpayClient>(); const [company, setCompany] = useState<NetpayCompany>(); const [branch, setBranch] = useState<NetpayBranch>();
  const [clientName, setClientName] = useState(''); const [companyName, setCompanyName] = useState(''); const [branchName, setBranchName] = useState(''); const [storeId, setStoreId] = useState(''); const [storeReferenceId, setStoreReferenceId] = useState<string | null>(null); const [matches, setMatches] = useState<NetpayClient[]>([]);
  const [description, setDescription] = useState(''); const [outcome, setOutcome] = useState(''); const [caseType, setCaseType] = useState('branch_onboarding'); const [product, setProduct] = useState('tpv'); const [priority, setPriority] = useState('normal'); const [sourceReference, setSourceReference] = useState('');
  const caseKey = useRef(newIdempotencyKey()); const masterKeys = useRef({ client: newIdempotencyKey(), company: newIdempotencyKey(), branch: newIdempotencyKey(), store: newIdempotencyKey() });
  async function submitMaster(event: FormEvent) { event.preventDefault(); setBusy(true); setNotice(''); try { const c = clientItem || await client.createClient({ display_name: clientName }, masterKeys.current.client); setClientItem(c); const co = await client.createCompany(c.id, { legal_name: companyName }, masterKeys.current.company); setCompany(co); const b = await client.createBranch(co.id, { commercial_name: branchName, branch_kind: 'physical' }, masterKeys.current.branch); setBranch(b); if (storeId) { const reference = await client.setStoreReference(b.id, { store_id: storeId, source_type: 'manual', confirmed: false }, masterKeys.current.store); setStoreReferenceId(reference.id); } setStep(2); } catch (reason) { setNotice(apiErrorMessage(reason)); } finally { setBusy(false); } }
  async function submitCase() { if (!clientItem || !company || !branch || busy) return; setBusy(true); setNotice(''); try { const item = await client.createCase({ client_id: clientItem.id, company_id: company.id, branch_id: branch.id, store_reference_id: storeReferenceId, case_type_key: caseType, original_description: description, expected_outcome: outcome || null, product, priority, source_channel: 'manual', source_reference: sourceReference || null, provenance: { capture: 'operator_ui' } }, caseKey.current); caseKey.current = newIdempotencyKey(); navigate(`/netpay-inbox/${item.id}`); } catch (reason) { setNotice(apiErrorMessage(reason)); } finally { setBusy(false); } }
  return <div className="netpay-modal" role="dialog" aria-modal="true" aria-labelledby="new-case-title"><section><button className="close" onClick={onClose} aria-label="Cerrar">×</button><h2 id="new-case-title">Nueva solicitud · paso {step} de 3</h2>{notice && <p role="alert" className="radar-notice">{notice}</p>}{step === 1 && <form onSubmit={submitMaster}><p>Busca primero para evitar duplicados.</p><label>Buscar Master<input aria-label="Buscar Master" onChange={async (e) => { if (e.target.value.length > 1) { const result = await client.listMaster(e.target.value); setMatches(result.items); setNotice(result.total ? `${result.total} posible(s) coincidencia(s).` : 'Sin coincidencias. Puedes crear el maestro.'); } }} /></label>{matches.map((match) => <button type="button" className="master-match" key={match.id} onClick={() => { setClientItem(match); setClientName(match.display_name); setMatches([]); setNotice(`Cliente existente seleccionado: ${match.display_name}`); }}>Usar {match.display_name}</button>)}<label>Cliente<input required value={clientName} onChange={(e) => { setClientItem(undefined); setClientName(e.target.value); }} /></label><label>Empresa<input required value={companyName} onChange={(e) => setCompanyName(e.target.value)} /></label><label>Sucursal<input required value={branchName} onChange={(e) => setBranchName(e.target.value)} /></label><label>Store ID opcional<input value={storeId} onChange={(e) => setStoreId(e.target.value)} /></label><button disabled={busy}>{busy ? 'Guardando…' : 'Guardar maestro y continuar'}</button></form>}{step === 2 && <form onSubmit={(e) => { e.preventDefault(); setStep(3); }}><label>Tipo<select value={caseType} onChange={(e) => setCaseType(e.target.value)}>{types.map((value) => <option key={value}>{value}</option>)}</select></label><label>Descripción original<textarea required value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Resultado esperado<textarea value={outcome} onChange={(e) => setOutcome(e.target.value)} /></label><label>Producto<select value={product} onChange={(e) => setProduct(e.target.value)}>{products.map((value) => <option key={value}>{value}</option>)}</select></label><label>Prioridad<select value={priority} onChange={(e) => setPriority(e.target.value)}>{priorities.map((value) => <option key={value}>{value}</option>)}</select></label><label>Canal<input value="manual" readOnly /></label><label>Referencia de origen<input value={sourceReference} onChange={(e) => setSourceReference(e.target.value)} /></label><button>Revisar</button></form>}{step === 3 && <div><h3>Revisión</h3><p>{clientName} → {companyName} → {branchName} → {storeId || 'Sin Store ID'}</p><p>{caseType} · {product} · {priority}</p><p>{description}</p><button disabled={busy} onClick={submitCase}>{busy ? 'Enviando…' : 'Crear caso'}</button></div>}</section></div>;
}

export function NetpayCaseDetail({ client = netpayApi }: { client?: NetpayApiClient }) {
  const { caseId = '' } = useParams(); const [item, setItem] = useState<NetpayCase>(); const [master, setMaster] = useState<NetpayClient>(); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  async function load() { try { const value = await client.getCase(caseId); setItem(value); if (value.branch_id) setMaster(await client.getMasterDetail(value.branch_id)); } catch (reason) { setError(apiErrorMessage(reason)); } }
  useEffect(() => { void load(); }, [caseId]);
  async function mutate(name: string, action: (key: string) => Promise<NetpayCase>) { if (busy) return; setBusy(name); setError(''); try { setItem(await action(newIdempotencyKey())); await load(); } catch (reason) { setError(apiErrorMessage(reason)); } finally { setBusy(''); } }
  if (error && !item) return <div role="alert"><p>{error}</p><button onClick={() => void load()}>Reintentar</button></div>; if (!item) return <p role="status">Cargando detalle…</p>;
  const company = master?.companies.find((value) => value.id === item.company_id); const branch = company?.branches.find((value) => value.id === item.branch_id); const canManage = client.can('netpay.inbox.manage'); const action = openAction(item);
  return <section className="netpay-detail"><Link to="/netpay-inbox">← Volver al Inbox</Link><header><p className="eyebrow">{item.folio}</p><h1>{master?.display_name || item.client_id}</h1><p>{company?.legal_name || item.company_id} → {branch?.commercial_name || 'Sin sucursal'} → {branch?.store_reference?.store_id || 'Sin Store ID'}</p><div className="case-tags"><span>{label(item.case_type_key)}</span><span>{label(item.product)}</span><span>{label(item.priority)}</span><span>{label(item.state)}</span></div></header>{error && <p role="alert" className="radar-notice">{error}</p>}<section className="next-action-panel"><h2>Siguiente acción</h2><strong>{action?.description || 'Sin siguiente acción'}</strong><p>{action ? `${action.responsible_principal_id || 'Sin responsable'} · ${date(action.due_date)}` : 'Define responsable y fecha para retirar ambigüedad.'}</p></section><div className="detail-grid"><article><h2>Solicitud original</h2><p>{item.original_description}</p><h3>Resultado esperado</h3><p>{item.expected_outcome || 'Pendiente'}</p><p>Responsable: {item.responsible_principal_id || 'Sin asignar'}</p></article><article><h2>Checklist</h2>{item.checklist.length ? item.checklist.map((check) => <div className="checkline" key={check.id}><span>{check.requirement_key} · {check.status}</span>{canManage && <button disabled={Boolean(busy)} onClick={() => void mutate('checklist', (key) => client.updateChecklist(item.id, check.id, { status: check.status === 'confirmed' ? 'missing' : 'confirmed', safe_evidence_reference: check.safe_evidence_reference, comment: null }, key))}>{check.status === 'confirmed' ? 'Marcar faltante' : 'Confirmar'}</button>}</div>) : <p>Sin checklist.</p>}</article><article><h2>Pasos internos</h2><ol>{item.steps.map((step) => <li key={step.id}>{step.description} · {step.status}</li>)}</ol></article><article><h2>Documentos</h2>{item.document_references.length ? item.document_references.map((doc) => <p key={doc.id}>{doc.status} · {doc.external_evidence_reference || 'Sin referencia'}</p>) : <p>Sin referencias documentales.</p>}</article></div>{canManage ? <MutationControls item={item} busy={busy} mutate={mutate} client={client} /> : <p className="read-only">Vista de sólo lectura. Las operaciones requieren netpay.inbox.manage.</p>}<section><h2>Bitácora</h2><ol className="timeline">{item.activities.map((activity) => <li key={activity.id}><strong>{label(activity.type)}</strong><p>{activity.summary}</p><time>{date(activity.created_at)}</time></li>)}</ol></section></section>;
}

function MutationControls({ item, busy, mutate, client }: { item: NetpayCase; busy: string; mutate: (name: string, action: (key: string) => Promise<NetpayCase>) => Promise<void>; client: NetpayApiClient }) {
  const [assignee, setAssignee] = useState(item.responsible_principal_id || ''); const [next, setNext] = useState(''); const [due, setDue] = useState(''); const [state, setState] = useState(item.state); const [reason, setReason] = useState(''); const [note, setNote] = useState('');
  return <section className="mutation-panel" aria-label="Operaciones del caso"><h2>Operar caso</h2><div><label>Principal responsable<input value={assignee} onChange={(e) => setAssignee(e.target.value)} placeholder="UUID o vacío para desasignar" /></label><button disabled={Boolean(busy)} onClick={() => void mutate('assignment', (key) => client.assignCase(item.id, { responsible_principal_id: assignee || null }, key))}>Guardar asignación</button></div><div><label>Siguiente acción<input value={next} onChange={(e) => setNext(e.target.value)} /></label><label>Fecha objetivo<input type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)} /></label><button disabled={Boolean(busy) || !next} onClick={() => void mutate('next-action', (key) => client.setNextAction(item.id, { description: next, responsible_principal_id: assignee || null, due_date: due ? new Date(due).toISOString() : null, status: 'open', origin: 'human' }, key))}>Definir acción</button></div><div><label>Nuevo estado<select value={state} onChange={(e) => setState(e.target.value)}>{states.map((value) => <option key={value}>{value}</option>)}</select></label><label>Motivo<input value={reason} onChange={(e) => setReason(e.target.value)} /></label><button disabled={Boolean(busy) || state === item.state} onClick={() => void mutate('state', (key) => client.transitionCase(item.id, { state, reason: reason || null }, key))}>Cambiar estado</button></div><div><label>Nota interna<textarea value={note} onChange={(e) => setNote(e.target.value)} /></label><button disabled={Boolean(busy) || !note} onClick={() => void mutate('activity', (key) => client.addActivity(item.id, { activity_type: 'operator_note', safe_summary: note, external_reference: null }, key))}>Agregar actividad</button></div></section>;
}
