"""Add tenant-owned D1 operational dataset persistence.

Revision ID: 20260819_41
Revises: 20260819_40
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260819_41"
down_revision = "20260819_40"
branch_labels = None
depends_on = None
U = postgresql.UUID(as_uuid=True)

def upgrade() -> None:
    op.create_table("netpay_operational_data_batches", sa.Column("id",U,primary_key=True),sa.Column("organization_id",U,nullable=False),sa.Column("dataset_type",sa.String(48),nullable=False),sa.Column("reporting_period",sa.String(16)),sa.Column("selected_sheet",sa.String(255),nullable=False),sa.Column("sanitized_filename",sa.String(255),nullable=False),sa.Column("source_hash",sa.String(64),nullable=False),sa.Column("preview_token",sa.String(64),nullable=False),sa.Column("store_state_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("row_counts",postgresql.JSONB(),nullable=False),sa.Column("source_discarded",sa.Boolean(),nullable=False),sa.Column("uploaded_by_principal_id",U,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["uploaded_by_principal_id"],["principals.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","dataset_type","source_hash",name="uq_netpay_data_batch_hash"),sa.CheckConstraint("dataset_type IN ('monthly_store_profitability','no_usage_campaign')",name="ck_netpay_data_batch_dataset"),sa.CheckConstraint("status IN ('uploaded','validating','needs_review','accepted','rejected')",name="ck_netpay_data_batch_status"))
    op.create_index("ix_netpay_data_batches_org_type_period","netpay_operational_data_batches",["organization_id","dataset_type","reporting_period"])
    op.create_table("netpay_operational_data_rows",sa.Column("id",U,primary_key=True),sa.Column("batch_id",U,nullable=False),sa.Column("source_row_number",sa.Integer(),nullable=False),sa.Column("controlled_payload",postgresql.JSONB(),nullable=False),sa.Column("validation_status",sa.String(16),nullable=False),sa.Column("match_status",sa.String(16),nullable=False),sa.Column("store_reference_id",U),sa.Column("error_codes",postgresql.JSONB(),nullable=False),sa.Column("row_key",sa.String(64),nullable=False),sa.Column("row_fingerprint",sa.String(64),nullable=False),sa.Column("projected_action",sa.String(16),nullable=False),sa.Column("resolved_by_principal_id",U),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["batch_id"],["netpay_operational_data_batches.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["store_reference_id"],["netpay_store_references.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["resolved_by_principal_id"],["principals.id"],ondelete="RESTRICT"),sa.UniqueConstraint("batch_id","source_row_number",name="uq_netpay_data_row_source"),sa.CheckConstraint("validation_status IN ('valid','invalid','needs_review')",name="ck_netpay_data_row_validation"),sa.CheckConstraint("match_status IN ('matched','unmatched','ambiguous')",name="ck_netpay_data_row_match"))
    op.create_index("ix_netpay_data_rows_batch_match","netpay_operational_data_rows",["batch_id","match_status"])
    for table, period, extra in (("netpay_store_profitability_facts","reporting_period",[sa.Column("client_external_reference",sa.String(100)),sa.Column("product_uen",sa.String(128)),sa.Column("volume",sa.Float()),sa.Column("transaction_count",sa.Integer()),sa.Column("income",sa.Float()),sa.Column("cost",sa.Float()),sa.Column("commissions",sa.Float()),sa.Column("profitability",sa.Float()),sa.Column("no_use_indicator",sa.Boolean()),sa.Column("row_fingerprint",sa.String(64),nullable=False)]),("netpay_no_usage_campaign_entries","campaign_period",[sa.Column("months_without_usage",sa.Integer()),sa.Column("merchant_status",sa.String(64)),sa.Column("alert_code",sa.String(64)),sa.Column("outcome_code",sa.String(64)),sa.Column("follow_up_code",sa.String(64)),sa.Column("row_fingerprint",sa.String(64),nullable=False)])):
        op.create_table(table,sa.Column("id",U,primary_key=True),sa.Column("organization_id",U,nullable=False),sa.Column("batch_id",U,nullable=False),sa.Column("store_reference_id",U,nullable=False),sa.Column(period,sa.String(16),nullable=False),*extra,sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["batch_id"],["netpay_operational_data_batches.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["store_reference_id"],["netpay_store_references.id"],ondelete="RESTRICT"),sa.UniqueConstraint("batch_id","store_reference_id",name="uq_netpay_profitability_batch_store" if table.endswith("profitability_facts") else "uq_netpay_no_usage_batch_store"))
        op.create_index("ix_netpay_profitability_org_store_period" if table.endswith("profitability_facts") else "ix_netpay_no_usage_org_store_period",table,["organization_id","store_reference_id",period])
    op.create_table("netpay_operational_data_command_receipts",sa.Column("id",U,primary_key=True),sa.Column("organization_id",U,nullable=False),sa.Column("command_type",sa.String(64),nullable=False),sa.Column("idempotency_key",sa.String(255),nullable=False),sa.Column("request_fingerprint",sa.String(64),nullable=False),sa.Column("actor_principal_id",U,nullable=False),sa.Column("result_batch_id",U,nullable=False),sa.Column("result_status_code",sa.Integer(),nullable=False),sa.Column("result_response_body",postgresql.JSONB(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["actor_principal_id"],["principals.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["result_batch_id"],["netpay_operational_data_batches.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","command_type","idempotency_key",name="uq_netpay_data_receipt_key"))

def downgrade() -> None:
    op.drop_table("netpay_operational_data_command_receipts")
    for table, index in (("netpay_no_usage_campaign_entries","ix_netpay_no_usage_org_store_period"),("netpay_store_profitability_facts","ix_netpay_profitability_org_store_period")):
        op.drop_index(index,table_name=table); op.drop_table(table)
    op.drop_table("netpay_operational_data_rows")
    op.drop_index("ix_netpay_data_batches_org_type_period",table_name="netpay_operational_data_batches")
    op.drop_table("netpay_operational_data_batches")
