"""mission inbox projection foundation

Revision ID: 20260726_13
Revises: 20260726_12
Create Date: 2026-07-26
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "20260726_13"
down_revision = "20260726_12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "domain_events",
        sa.Column("event_sequence", sa.BigInteger(), nullable=True),
    )
    op.execute(
        """
        WITH ordered_events AS (
            SELECT id, row_number() OVER (ORDER BY occurred_at, recorded_at, id) AS sequence
            FROM domain_events
        )
        UPDATE domain_events
        SET event_sequence = ordered_events.sequence
        FROM ordered_events
        WHERE domain_events.id = ordered_events.id
        """
    )
    op.alter_column("domain_events", "event_sequence", nullable=False)
    op.execute("ALTER TABLE domain_events ALTER COLUMN event_sequence ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('domain_events', 'event_sequence'), "
        "COALESCE(MAX(event_sequence), 1), MAX(event_sequence) IS NOT NULL) FROM domain_events"
    )
    op.create_unique_constraint("uq_domain_events_event_sequence", "domain_events", ["event_sequence"])

    op.create_table(
        "mission_inbox_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_type", sa.String(length=100), nullable=False),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("intake_item_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("site_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("connector_mapping_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=50), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("projected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_event_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("projection_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["intake_item_id"], ["intake_items.id"]),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"]),
        sa.ForeignKeyConstraint(["connector_mapping_id"], ["connector_mappings.id"]),
        sa.ForeignKeyConstraint(["source_event_id"], ["domain_events.id"]),
        sa.UniqueConstraint("organization_id", "source_type", "source_id", name="uq_mission_inbox_items_source_identity"),
    )
    op.create_index("ix_mission_inbox_items_status", "mission_inbox_items", ["status"])
    op.create_index("ix_mission_inbox_items_priority", "mission_inbox_items", ["priority"])
    op.create_index("ix_mission_inbox_items_received_at", "mission_inbox_items", ["received_at"])
    op.create_index("ix_mission_inbox_items_last_activity_at", "mission_inbox_items", ["last_activity_at"])
    op.create_index("ix_mission_inbox_items_project_id", "mission_inbox_items", ["project_id"])
    op.create_index("ix_mission_inbox_items_site_id", "mission_inbox_items", ["site_id"])

    op.create_table(
        "projection_checkpoints",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("projection_name", sa.String(length=100), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("last_event_sequence", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("projection_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.UniqueConstraint("projection_name", name="uq_projection_checkpoints_projection_name"),
    )


def downgrade() -> None:
    op.drop_table("projection_checkpoints")
    op.drop_index("ix_mission_inbox_items_site_id", table_name="mission_inbox_items")
    op.drop_index("ix_mission_inbox_items_project_id", table_name="mission_inbox_items")
    op.drop_index("ix_mission_inbox_items_last_activity_at", table_name="mission_inbox_items")
    op.drop_index("ix_mission_inbox_items_received_at", table_name="mission_inbox_items")
    op.drop_index("ix_mission_inbox_items_priority", table_name="mission_inbox_items")
    op.drop_index("ix_mission_inbox_items_status", table_name="mission_inbox_items")
    op.drop_table("mission_inbox_items")
    op.drop_constraint("uq_domain_events_event_sequence", "domain_events", type_="unique")
    op.drop_column("domain_events", "event_sequence")
