import {render,screen} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {expect,it,vi} from 'vitest';
import {useState} from 'react';
import type {RecoveryQueueFilters as Filters} from '../../types/storeIntelligence';
import {RecoveryQueueFilters} from './RecoveryQueueFilters';

function Harness({initial={},spy=vi.fn()}:{initial?:Filters;spy?:ReturnType<typeof vi.fn>}){const [value,setValue]=useState<Filters>(initial);return <><RecoveryQueueFilters value={value} onChange={v=>{setValue(v);spy(v)}} onReset={()=>{setValue({});spy({})}}/><output>{JSON.stringify(value)}</output></>}
it('updates the supported typed filters and preserves explicit false with combined state',async()=>{const spy=vi.fn();render(<Harness initial={{operational_block:false}} spy={spy}/>);const u=userEvent.setup();await u.selectOptions(screen.getByLabelText('Pendiente'),'false');await u.type(screen.getByLabelText('Cliente'),'synthetic');await u.clear(screen.getByLabelText('Meses mínimos'));await u.type(screen.getByLabelText('Meses mínimos'),'0');await u.selectOptions(screen.getByLabelText('Completitud'),'partial');expect(spy).toHaveBeenLastCalledWith({operational_block:false,pending_action:false,client_id:'synthetic',minimum_months_no_use:0,evidence_completeness:'partial'});expect(screen.getByText(/"pending_action":false/)).toBeTruthy();});
it('distinguishes all and true, normalizes empty client id, resets, and has no fuzzy or ranking control',async()=>{const spy=vi.fn();render(<Harness initial={{client_id:'synthetic'}} spy={spy}/>);const u=userEvent.setup();await u.selectOptions(screen.getByLabelText('Pendiente'),'true');expect(spy).toHaveBeenLastCalledWith({client_id:'synthetic',pending_action:true});await u.selectOptions(screen.getByLabelText('Pendiente'),'');expect(spy).toHaveBeenLastCalledWith({client_id:'synthetic',pending_action:undefined});await u.clear(screen.getByLabelText('Cliente'));expect(spy).toHaveBeenLastCalledWith({client_id:undefined});await u.click(screen.getByRole('button',{name:'Restablecer'}));expect(spy).toHaveBeenLastCalledWith({});expect(screen.queryByLabelText(/store.?name|prioridad|ranking|recommendation/i)).toBeNull();});
