"""Explicit canonical Tier 1 Interaction Contract declarations for Yarvis."""

from yarvis_api.contract_registry import (
    ContractCriticality,
    ContractDefinition,
    ContractLifecycle,
    ContractOperationalStatus,
    ContractType,
)

CANONICAL_CONTRACTS: tuple[ContractDefinition, ...] = (
    ContractDefinition(
        interaction_contract_id="IC-IDENTITY-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="identity",
        owning_context="Identity",
        owning_capability="resolution",
        name="ResolveSubjectCandidate",
        semantic_purpose="resolve or propose canonical Party/PartyGroup reference",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="intake association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-IDENTITY-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="identity",
        owning_context="Identity",
        owning_capability="canonical reference",
        name="RetrieveCanonicalIdentity",
        semantic_purpose="RetrieveCanonicalIdentity",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="all Tier 1 association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-IDENTITY-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="identity",
        owning_context="Identity",
        owning_capability="resolution",
        name="IdentityResolutionRecorded",
        semantic_purpose="IdentityResolutionRecorded",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="O&E, Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-GOVERNANCE-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="governance",
        owning_context="Governance",
        owning_capability="authority",
        name="EvaluateAuthority",
        semantic_purpose="EvaluateAuthority",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="target-command authorization",
    ),
    ContractDefinition(
        interaction_contract_id="IC-GOVERNANCE-QRY-002",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="governance",
        owning_context="Governance",
        owning_capability="policy/delegation",
        name="RetrieveApplicableDelegation",
        semantic_purpose="RetrieveApplicableDelegation",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="work assignment",
    ),
    ContractDefinition(
        interaction_contract_id="IC-GOVERNANCE-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="governance",
        owning_context="Governance",
        owning_capability="authority",
        name="AuthorityChanged",
        semantic_purpose="AuthorityChanged",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Execution, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-RELATIONSHIP-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="relationship",
        owning_context="Relationship",
        owning_capability="association",
        name="EstablishCasePartyRelationship",
        semantic_purpose="EstablishCasePartyRelationship",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="merchant/case association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-RELATIONSHIP-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="relationship",
        owning_context="Relationship",
        owning_capability="association",
        name="RetrieveCaseRelationships",
        semantic_purpose="RetrieveCaseRelationships",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="case view",
    ),
    ContractDefinition(
        interaction_contract_id="IC-RELATIONSHIP-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="relationship",
        owning_context="Relationship",
        owning_capability="association",
        name="RelationshipRecorded",
        semantic_purpose="RelationshipRecorded",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="observation",
        name="CaptureInboundObservation",
        semantic_purpose="CaptureInboundObservation",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Inbox First intake",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-CMD-002",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="artifact/evidence",
        name="RegisterSourceArtifact",
        semantic_purpose="RegisterSourceArtifact",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="document or attachment",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-CMD-003",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="validation",
        name="ValidateEvidence",
        semantic_purpose="ValidateEvidence",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="checklist evidence",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="lineage",
        name="RetrieveEvidenceStatus",
        semantic_purpose="RetrieveEvidenceStatus",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="checklist/case view",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="observation",
        name="ObservationCaptured",
        semantic_purpose="ObservationCaptured",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="identity and Netpay intake",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-EVT-002",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="evidence",
        name="EvidenceValidated",
        semantic_purpose="EvidenceValidated",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Knowledge, Netpay",
    ),
    ContractDefinition(
        interaction_contract_id="IC-KNOWLEDGE-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="knowledge",
        owning_context="Knowledge",
        owning_capability="promotion",
        name="ActivateCaseKnowledge",
        semantic_purpose="ActivateCaseKnowledge",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="governed case facts",
    ),
    ContractDefinition(
        interaction_contract_id="IC-KNOWLEDGE-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="knowledge",
        owning_context="Knowledge",
        owning_capability="assertion",
        name="RetrieveActiveCaseKnowledge",
        semantic_purpose="RetrieveActiveCaseKnowledge",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay case handling",
    ),
    ContractDefinition(
        interaction_contract_id="IC-KNOWLEDGE-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="knowledge",
        owning_context="Knowledge",
        owning_capability="assertion",
        name="KnowledgeActivated",
        semantic_purpose="KnowledgeActivated",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work",
        name="CreatePendingAction",
        semantic_purpose="CreatePendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="missing-document work",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-CMD-002",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="assignment",
        name="AssignPendingAction",
        semantic_purpose="AssignPendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="operator responsibility",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-CMD-003",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work state",
        name="ResolvePendingAction",
        semantic_purpose="ResolvePendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="complete, cancel, or escalate action",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work state",
        name="RetrievePendingActionStatus",
        semantic_purpose="RetrievePendingActionStatus",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="case and MC views",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work",
        name="PendingActionStateChanged",
        semantic_purpose="PendingActionStateChanged",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-EVT-002",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="activity",
        name="WorkActivityRecorded",
        semantic_purpose="WorkActivityRecorded",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="case history",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="acknowledgement",
        name="AcknowledgeAttentionItem",
        semantic_purpose="AcknowledgeAttentionItem",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="human acknowledgement",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="attention projection",
        name="RetrieveCaseAttention",
        semantic_purpose="RetrieveCaseAttention",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="operator work surface",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="projection",
        name="AttentionPublished",
        semantic_purpose="AttentionPublished",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="operator surfaces",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-NTF-001",
        version="1.0.0",
        contract_type=ContractType.NOTIFICATION,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="communication",
        name="NotifyAttentionRecipient",
        semantic_purpose="NotifyAttentionRecipient",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.INFORMATIONAL,
        primary_consumer_or_use_case="relevant actor",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="merchant candidate",
        name="IdentifyOrRegisterMerchantCandidate",
        semantic_purpose="IdentifyOrRegisterMerchantCandidate",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="inbox association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-002",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case",
        name="OpenNetpayOnboardingOrServiceCase",
        semantic_purpose="OpenNetpayOnboardingOrServiceCase",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="TPV/e-commerce service case",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-003",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case classification",
        name="ClassifyNetpayChannel",
        semantic_purpose="ClassifyNetpayChannel",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="TPV, e-commerce, or mixed",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-004",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="checklist",
        name="EvaluateChecklistAndSetPendingAction",
        semantic_purpose="EvaluateChecklistAndSetPendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="missing-document detection; invokes owner contracts",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case view",
        name="RetrieveMerchantCase",
        semantic_purpose="RetrieveMerchantCase",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="case handling",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-QRY-002",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="checklist view",
        name="RetrieveChecklistAndPendingActions",
        semantic_purpose="RetrieveChecklistAndPendingActions",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="operator view",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case",
        name="NetpayCaseOpened",
        semantic_purpose="NetpayCaseOpened",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Execution, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-EVT-002",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case",
        name="NetpayCaseStatusChanged",
        semantic_purpose="NetpayCaseStatusChanged",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="MC, notification",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-NTF-001",
        version="1.0.0",
        contract_type=ContractType.NOTIFICATION,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="communication",
        name="NotifyCaseActor",
        semantic_purpose="NotifyCaseActor",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="assigned/relevant actor",
    ),
)


def canonical_contracts() -> tuple[ContractDefinition, ...]:
    """Return the immutable, explicit canonical Tier 1 contract baseline."""

    return CANONICAL_CONTRACTS
