"""Explicit canonical Tier 1 Interaction Contract declarations for Yarvis."""

from yarvis_api.contract_registry import (
    ContractCriticality,
    ContractDefinition,
    ContractLifecycle,
    ContractOperationalStatus,
    ContractType,
)

CANONICAL_CONTRACTS: tuple[ContractDefinition, ...] = (
    ContractDefinition(
        interaction_contract_id="IC-PLATFORM-CMD-DISPATCH-PROBE",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="platform",
        owning_context="Platform",
        owning_capability="dispatch mechanics",
        name="DispatchMechanicsProbe",
        semantic_purpose="Prove zero-persistence synchronous Dispatch mechanics",
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.VERIFIED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Dispatch mechanics probe",
    ),
    ContractDefinition(
        interaction_contract_id="IC-WORKSPACE-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="operational workspace overview",
        name="RetrieveOperationalWorkspaceOverview",
        semantic_purpose="Retrieve tenant-safe operational workspace composition",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Operational Workspace",
    ),
    ContractDefinition(
        interaction_contract_id="IC-TASK-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="operational_execution",
        owning_context="Operational Execution",
        owning_capability="task creation",
        name="CreateOperationalTask",
        semantic_purpose="Create an operational task",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Mission Work task",
    ),
    ContractDefinition(
        interaction_contract_id="IC-TASK-CMD-002",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="operational_execution",
        owning_context="Operational Execution",
        owning_capability="task planning",
        name="UpdateOperationalTaskPlanningFields",
        semantic_purpose="Update planned task fields",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Mission Work task",
    ),
    ContractDefinition(
        interaction_contract_id="IC-TASK-CMD-003",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="operational_execution",
        owning_context="Operational Execution",
        owning_capability="task assignment",
        name="AssignOperationalTask",
        semantic_purpose="Assign an operational task",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Mission Work task",
    ),
    ContractDefinition(
        interaction_contract_id="IC-TASK-CMD-004",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="operational_execution",
        owning_context="Operational Execution",
        owning_capability="task transition",
        name="TransitionOperationalTask",
        semantic_purpose="Transition operational task lifecycle",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Mission Work task",
    ),
    ContractDefinition(
        interaction_contract_id="IC-TASK-CMD-005",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="operational_execution",
        owning_context="Operational Execution",
        owning_capability="task completion",
        name="CompleteOperationalTask",
        semantic_purpose="Explicitly complete an operational task",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Mission Work task",
    ),
    ContractDefinition(
        interaction_contract_id="IC-TASK-CMD-006",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="operational_execution",
        owning_context="Operational Execution",
        owning_capability="task cancellation",
        name="CancelOperationalTask",
        semantic_purpose="Explicitly cancel an operational task",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Mission Work task",
    ),
    ContractDefinition(
        interaction_contract_id="IC-TASK-CMD-007",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="operational_execution",
        owning_context="Operational Execution",
        owning_capability="task dependencies",
        name="ManageOperationalTaskDependencies",
        semantic_purpose="Manage direct finish-to-start dependencies",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Mission Work task",
    ),
    ContractDefinition(
        interaction_contract_id="IC-IDENTITY-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="identity",
        owning_context="Identity",
        owning_capability="resolution",
        name="ResolveSubjectCandidate",
        semantic_purpose="resolve or propose canonical Party/PartyGroup reference",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="intake association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-IDENTITY-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="identity",
        owning_context="Identity",
        owning_capability="canonical reference",
        name="RetrieveCanonicalIdentity",
        semantic_purpose="RetrieveCanonicalIdentity",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="all Tier 1 association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-IDENTITY-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="identity",
        owning_context="Identity",
        owning_capability="resolution",
        name="IdentityResolutionRecorded",
        semantic_purpose="IdentityResolutionRecorded",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="O&E, Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-GOVERNANCE-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="governance",
        owning_context="Governance",
        owning_capability="authority",
        name="EvaluateAuthority",
        semantic_purpose="EvaluateAuthority",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="target-command authorization",
    ),
    ContractDefinition(
        interaction_contract_id="IC-GOVERNANCE-QRY-002",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="governance",
        owning_context="Governance",
        owning_capability="policy/delegation",
        name="RetrieveApplicableDelegation",
        semantic_purpose="RetrieveApplicableDelegation",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="work assignment",
    ),
    ContractDefinition(
        interaction_contract_id="IC-GOVERNANCE-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="governance",
        owning_context="Governance",
        owning_capability="authority",
        name="AuthorityChanged",
        semantic_purpose="AuthorityChanged",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Execution, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-RELATIONSHIP-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="relationship",
        owning_context="Relationship",
        owning_capability="association",
        name="EstablishCasePartyRelationship",
        semantic_purpose="EstablishCasePartyRelationship",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="merchant/case association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-RELATIONSHIP-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="relationship",
        owning_context="Relationship",
        owning_capability="association",
        name="RetrieveCaseRelationships",
        semantic_purpose="RetrieveCaseRelationships",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="case view",
    ),
    ContractDefinition(
        interaction_contract_id="IC-RELATIONSHIP-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="relationship",
        owning_context="Relationship",
        owning_capability="association",
        name="RelationshipRecorded",
        semantic_purpose="RelationshipRecorded",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="observation",
        name="CaptureInboundObservation",
        semantic_purpose="CaptureInboundObservation",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Inbox First intake",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-CMD-002",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="artifact/evidence",
        name="RegisterSourceArtifact",
        semantic_purpose="RegisterSourceArtifact",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="document or attachment",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-CMD-003",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="validation",
        name="ValidateEvidence",
        semantic_purpose="ValidateEvidence",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="checklist evidence",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="lineage",
        name="RetrieveEvidenceStatus",
        semantic_purpose="RetrieveEvidenceStatus",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="checklist/case view",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="observation",
        name="ObservationCaptured",
        semantic_purpose="ObservationCaptured",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="identity and Netpay intake",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EVIDENCE-EVT-002",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="observation_evidence",
        owning_context="Observation & Evidence",
        owning_capability="evidence",
        name="EvidenceValidated",
        semantic_purpose="EvidenceValidated",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Knowledge, Netpay",
    ),
    ContractDefinition(
        interaction_contract_id="IC-KNOWLEDGE-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="knowledge",
        owning_context="Knowledge",
        owning_capability="promotion",
        name="ActivateCaseKnowledge",
        semantic_purpose="ActivateCaseKnowledge",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="governed case facts",
    ),
    ContractDefinition(
        interaction_contract_id="IC-KNOWLEDGE-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="knowledge",
        owning_context="Knowledge",
        owning_capability="assertion",
        name="RetrieveActiveCaseKnowledge",
        semantic_purpose="RetrieveActiveCaseKnowledge",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay case handling",
    ),
    ContractDefinition(
        interaction_contract_id="IC-KNOWLEDGE-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="knowledge",
        owning_context="Knowledge",
        owning_capability="assertion",
        name="KnowledgeActivated",
        semantic_purpose="KnowledgeActivated",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work",
        name="CreatePendingAction",
        semantic_purpose="CreatePendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="missing-document work",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-CMD-002",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="assignment",
        name="AssignPendingAction",
        semantic_purpose="AssignPendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="operator responsibility",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-CMD-003",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work state",
        name="ResolvePendingAction",
        semantic_purpose="ResolvePendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="complete, cancel, or escalate action",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work state",
        name="RetrievePendingActionStatus",
        semantic_purpose="RetrievePendingActionStatus",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="case and MC views",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="work",
        name="PendingActionStateChanged",
        semantic_purpose="PendingActionStateChanged",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Netpay, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-EXECUTION-EVT-002",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="execution",
        owning_context="Execution",
        owning_capability="activity",
        name="WorkActivityRecorded",
        semantic_purpose="WorkActivityRecorded",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="case history",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="acknowledgement",
        name="AcknowledgeAttentionItem",
        semantic_purpose="AcknowledgeAttentionItem",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="human acknowledgement",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="attention projection",
        name="RetrieveCaseAttention",
        semantic_purpose="RetrieveCaseAttention",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="operator work surface",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="projection",
        name="AttentionPublished",
        semantic_purpose="AttentionPublished",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="operator surfaces",
    ),
    ContractDefinition(
        interaction_contract_id="IC-MISSION-NTF-001",
        version="1.0.0",
        contract_type=ContractType.NOTIFICATION,
        owner_module_id="mission_control",
        owning_context="Mission Control",
        owning_capability="communication",
        name="NotifyAttentionRecipient",
        semantic_purpose="NotifyAttentionRecipient",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.INFORMATIONAL,
        primary_consumer_or_use_case="relevant actor",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-001",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="merchant candidate",
        name="IdentifyOrRegisterMerchantCandidate",
        semantic_purpose="IdentifyOrRegisterMerchantCandidate",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="inbox association",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-002",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case",
        name="OpenNetpayOnboardingOrServiceCase",
        semantic_purpose="OpenNetpayOnboardingOrServiceCase",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="TPV/e-commerce service case",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-003",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case classification",
        name="ClassifyNetpayChannel",
        semantic_purpose="ClassifyNetpayChannel",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="TPV, e-commerce, or mixed",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-CMD-004",
        version="1.0.0",
        contract_type=ContractType.COMMAND,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="checklist",
        name="EvaluateChecklistAndSetPendingAction",
        semantic_purpose="EvaluateChecklistAndSetPendingAction",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="missing-document detection; invokes owner contracts",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-QRY-001",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case view",
        name="RetrieveMerchantCase",
        semantic_purpose="RetrieveMerchantCase",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="case handling",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-QRY-002",
        version="1.0.0",
        contract_type=ContractType.QUERY,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="checklist view",
        name="RetrieveChecklistAndPendingActions",
        semantic_purpose="RetrieveChecklistAndPendingActions",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="operator view",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-EVT-001",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case",
        name="NetpayCaseOpened",
        semantic_purpose="NetpayCaseOpened",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="Execution, MC",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-EVT-002",
        version="1.0.0",
        contract_type=ContractType.EVENT,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="case",
        name="NetpayCaseStatusChanged",
        semantic_purpose="NetpayCaseStatusChanged",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case="MC, notification",
    ),
    ContractDefinition(
        interaction_contract_id="IC-NETPAY-NTF-001",
        version="1.0.0",
        contract_type=ContractType.NOTIFICATION,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="communication",
        name="NotifyCaseActor",
        semantic_purpose="NotifyCaseActor",
        lifecycle=ContractLifecycle.PROPOSED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.OPERATIONAL,
        primary_consumer_or_use_case="assigned/relevant actor",
    ),
)

CANONICAL_CONTRACTS += tuple(
    ContractDefinition(
        interaction_contract_id=contract_id,
        version="1.0.0",
        contract_type=contract_type,
        owner_module_id="document_registry",
        owning_context="Document Registry",
        owning_capability=capability,
        name=name,
        semantic_purpose=purpose,
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.VERIFIED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Document Registry",
    )
    for contract_id, contract_type, capability, name, purpose in (
        (
            "IC-DOCUMENT-CMD-001",
            ContractType.COMMAND,
            "document creation",
            "CreateDocument",
            "Create a governed Document",
        ),
        (
            "IC-DOCUMENT-CMD-002",
            ContractType.COMMAND,
            "metadata update",
            "UpdateDocumentMetadata",
            "Update governed Document metadata",
        ),
        (
            "IC-DOCUMENT-CMD-003",
            ContractType.COMMAND,
            "version creation",
            "AddDocumentVersion",
            "Append immutable Document Version metadata",
        ),
        (
            "IC-DOCUMENT-CMD-004",
            ContractType.COMMAND,
            "document archival",
            "ArchiveDocument",
            "Archive a governed Document",
        ),
        (
            "IC-DOCUMENT-CMD-005",
            ContractType.COMMAND,
            "association link",
            "LinkDocumentAssociation",
            "Link a governed Document association",
        ),
        (
            "IC-DOCUMENT-CMD-006",
            ContractType.COMMAND,
            "association unlink",
            "UnlinkDocumentAssociation",
            "Historically unlink a Document association",
        ),
        (
            "IC-DOCUMENT-QRY-001",
            ContractType.QUERY,
            "document retrieval",
            "GetDocument",
            "Retrieve a tenant-safe Document",
        ),
        (
            "IC-DOCUMENT-QRY-002",
            ContractType.QUERY,
            "version retrieval",
            "GetDocumentVersions",
            "Retrieve immutable Document Versions",
        ),
        (
            "IC-DOCUMENT-QRY-003",
            ContractType.QUERY,
            "association retrieval",
            "GetDocumentAssociations",
            "Retrieve active Document associations",
        ),
        (
            "IC-DOCUMENT-QRY-004",
            ContractType.QUERY,
            "subject retrieval",
            "GetDocumentsBySubject",
            "Retrieve Documents actively associated with a subject",
        ),
    )
)

CANONICAL_CONTRACTS += tuple(
    ContractDefinition(
        interaction_contract_id=i,
        version="1.0.0",
        contract_type=t,
        owner_module_id=o,
        owning_context=c,
        owning_capability=k,
        name=n,
        semantic_purpose=p,
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CRITICAL,
        primary_consumer_or_use_case=u,
    )
    for i, t, o, c, k, n, p, u in (
        (
            "IC-IDENTITY-CMD-002",
            ContractType.COMMAND,
            "identity",
            "Identity",
            "external identity binding",
            "BindExternalIdentity",
            "Bind verified external identity",
            "productive identity",
        ),
        (
            "IC-IDENTITY-CMD-003",
            ContractType.COMMAND,
            "identity",
            "Identity",
            "person principal association",
            "LinkPrincipalToPerson",
            "Link human Principal to canonical Person",
            "productive identity",
        ),
        (
            "IC-IDENTITY-CMD-004",
            ContractType.COMMAND,
            "identity",
            "Identity",
            "productive session",
            "StartProductiveSession",
            "Start server-side productive session",
            "productive access",
        ),
        (
            "IC-IDENTITY-CMD-005",
            ContractType.COMMAND,
            "identity",
            "Identity",
            "productive session",
            "RevokeProductiveSession",
            "Terminally revoke productive session",
            "productive access",
        ),
        (
            "IC-IDENTITY-QRY-002",
            ContractType.QUERY,
            "identity",
            "Identity",
            "principal resolution",
            "ResolvePrincipal",
            "Resolve active Principal from verified binding",
            "authentication boundary",
        ),
        (
            "IC-IDENTITY-QRY-003",
            ContractType.QUERY,
            "identity",
            "Identity",
            "productive session",
            "GetCurrentSession",
            "Retrieve safe current session projection",
            "web application",
        ),
        (
            "IC-IDENTITY-EVT-002",
            ContractType.EVENT,
            "identity",
            "Identity",
            "external identity binding",
            "ExternalIdentityBound",
            "External identity binding recorded",
            "security audit",
        ),
        (
            "IC-IDENTITY-EVT-003",
            ContractType.EVENT,
            "identity",
            "Identity",
            "person principal association",
            "PrincipalLinkedToPerson",
            "Principal linked to canonical Person",
            "authority resolution",
        ),
        (
            "IC-IDENTITY-EVT-004",
            ContractType.EVENT,
            "identity",
            "Identity",
            "productive session",
            "ProductiveSessionStarted",
            "Productive session started",
            "security audit",
        ),
        (
            "IC-IDENTITY-EVT-005",
            ContractType.EVENT,
            "identity",
            "Identity",
            "productive session",
            "ProductiveSessionRevoked",
            "Productive session terminally revoked",
            "authorization invalidation",
        ),
        (
            "IC-GOVERNANCE-CMD-001",
            ContractType.COMMAND,
            "governance",
            "Governance",
            "membership",
            "GrantMembership",
            "Grant explicit active Membership",
            "canonical authority",
        ),
        (
            "IC-GOVERNANCE-CMD-002",
            ContractType.COMMAND,
            "governance",
            "Governance",
            "membership",
            "RevokeMembership",
            "Terminally revoke Membership",
            "authority withdrawal",
        ),
        (
            "IC-GOVERNANCE-CMD-003",
            ContractType.COMMAND,
            "governance",
            "Governance",
            "bootstrap",
            "CloseBootstrapWindow",
            "Terminally close bootstrap window",
            "bootstrap administration",
        ),
        (
            "IC-GOVERNANCE-QRY-003",
            ContractType.QUERY,
            "governance",
            "Governance",
            "membership resolution",
            "ResolveEffectiveMembership",
            "Resolve effective Membership and Organization",
            "authority envelope",
        ),
        (
            "IC-GOVERNANCE-QRY-004",
            ContractType.QUERY,
            "governance",
            "Governance",
            "bootstrap",
            "GetBootstrapEligibility",
            "Get minimal bootstrap eligibility",
            "bootstrap administration",
        ),
        (
            "IC-GOVERNANCE-EVT-002",
            ContractType.EVENT,
            "governance",
            "Governance",
            "bootstrap",
            "BootstrapWindowClosed",
            "Bootstrap window terminally closed",
            "security audit",
        ),
    )
)

CANONICAL_CONTRACTS += tuple(
    ContractDefinition(
        interaction_contract_id=contract_id,
        version="1.0.0",
        contract_type=contract_type,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="Netpay Gmail intake",
        name=name,
        semantic_purpose=purpose,
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay MVP-2D1 Manual Review Variant",
        architectural_steward=None,
        traceability_references=(
            "IMPLEMENTATION_ROADMAP_AMENDMENT_018.md",
            "NETPAY_MVP2D1_CONTRACT_AND_ROLE_ALLOCATION_PROPOSAL.md",
            "ADR-019_RATIFY_NETPAY_MVP2D1_CONTRACT_AND_ROLE_ALLOCATION.md",
        ),
    )
    for contract_id, contract_type, name, purpose in (
        (
            "IC-NETPAY-CMD-016",
            ContractType.COMMAND,
            "ConfigureNetpayGmailConnector",
            "Define logical configuration and lifecycle transitions for one explicit, Organization-bound mailbox "
            "configuration",
        ),
        (
            "IC-NETPAY-CMD-017",
            ContractType.COMMAND,
            "SynchronizeNetpayGmailConnector",
            "Represent a future human-triggered synchronization request for one explicit mailbox configuration",
        ),
        (
            "IC-NETPAY-CMD-018",
            ContractType.COMMAND,
            "ReviewNetpayIntakeCandidate",
            "Record an explicit human review of one tenant-owned candidate",
        ),
        (
            "IC-NETPAY-QRY-007",
            ContractType.QUERY,
            "ListNetpayIntakeCandidates",
            "Return a tenant-scoped list of safe candidate summaries and an allowlisted connector-health summary",
        ),
        (
            "IC-NETPAY-QRY-008",
            ContractType.QUERY,
            "RetrieveNetpayIntakeCandidate",
            "Return one safe, tenant-scoped candidate detail for human review",
        ),
        (
            "IC-NETPAY-EVT-007",
            ContractType.EVENT,
            "NetpayIntakeCandidateReceived",
            "Record receipt of a tenant-owned Netpay intake candidate",
        ),
        (
            "IC-NETPAY-EVT-008",
            ContractType.EVENT,
            "NetpayIntakeCandidateReviewed",
            "Record an explicit human review of a tenant-owned Netpay intake candidate",
        ),
        (
            "IC-NETPAY-EVT-010",
            ContractType.EVENT,
            "NetpayGmailConnectorSyncFailed",
            "Record a safe Netpay Gmail connector synchronization failure fact",
        ),
    )
)

CANONICAL_CONTRACTS += tuple(
    ContractDefinition(
        interaction_contract_id=contract_id,
        version="1.0.0",
        contract_type=contract_type,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="commercial intake pre-master",
        name=name,
        semantic_purpose=purpose,
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay commercial intake",
    )
    for contract_id, contract_type, name, purpose in (
        (
            "IC-NETPAY-CMD-020",
            ContractType.COMMAND,
            "CreateCommercialIntake",
            "Create a tenant-owned pre-Master commercial intake item",
        ),
        (
            "IC-NETPAY-CMD-021",
            ContractType.COMMAND,
            "UpdateCommercialIntakeQualification",
            "Update commercial intake qualification",
        ),
        ("IC-NETPAY-CMD-022", ContractType.COMMAND, "AssignCommercialIntake", "Assign commercial intake"),
        (
            "IC-NETPAY-CMD-023",
            ContractType.COMMAND,
            "SetCommercialIntakeNextAction",
            "Set commercial intake next action",
        ),
        ("IC-NETPAY-CMD-024", ContractType.COMMAND, "DiscardCommercialIntake", "Discard commercial intake"),
        (
            "IC-NETPAY-CMD-025",
            ContractType.COMMAND,
            "ConvertCommercialIntakeToServiceCase",
            "Convert qualified commercial intake to Netpay service case",
        ),
        ("IC-NETPAY-QRY-009", ContractType.QUERY, "GetCommercialIntake", "Retrieve one commercial intake"),
        ("IC-NETPAY-QRY-010", ContractType.QUERY, "ListCommercialIntake", "List tenant-scoped commercial intake"),
        ("IC-NETPAY-EVT-011", ContractType.EVENT, "CommercialIntakeCreated", "Record commercial intake creation"),
        ("IC-NETPAY-EVT-012", ContractType.EVENT, "CommercialIntakeChanged", "Record commercial intake change"),
        ("IC-NETPAY-EVT-013", ContractType.EVENT, "CommercialIntakeConverted", "Record commercial intake conversion"),
        ("IC-NETPAY-EVT-014", ContractType.EVENT, "CommercialIntakeDiscarded", "Record commercial intake discard"),
    )
)

CANONICAL_CONTRACTS += tuple(
    ContractDefinition(
        interaction_contract_id=contract_id,
        version="1.0.0",
        contract_type=contract_type,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="operational data intake D1",
        name=name,
        semantic_purpose=purpose,
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay operational dataset intake",
    )
    for contract_id, contract_type, name, purpose in (
        (
            "IC-NETPAY-CMD-026",
            ContractType.COMMAND,
            "UploadOperationalDataset",
            "Upload and stage a tenant-scoped operational dataset",
        ),
        (
            "IC-NETPAY-CMD-027",
            ContractType.COMMAND,
            "ValidateOperationalDataset",
            "Validate controlled operational dataset rows",
        ),
        (
            "IC-NETPAY-CMD-028",
            ContractType.COMMAND,
            "AcceptOperationalDataset",
            "Accept a validated operational dataset and append facts",
        ),
        (
            "IC-NETPAY-CMD-029",
            ContractType.COMMAND,
            "RejectOperationalDataset",
            "Reject a staged operational dataset without deleting evidence",
        ),
        (
            "IC-NETPAY-CMD-030",
            ContractType.COMMAND,
            "ResolveOperationalRowMatch",
            "Resolve one operational row to a same-tenant Store Reference",
        ),
        (
            "IC-NETPAY-QRY-011",
            ContractType.QUERY,
            "PreviewOperationalDataset",
            "Retrieve a sanitized operational dataset preview",
        ),
        (
            "IC-NETPAY-QRY-012",
            ContractType.QUERY,
            "GetOperationalDatasetBatch",
            "Retrieve one tenant-scoped operational dataset batch",
        ),
        (
            "IC-NETPAY-QRY-013",
            ContractType.QUERY,
            "ListOperationalDatasetBatches",
            "List tenant-scoped operational dataset batches",
        ),
        (
            "IC-NETPAY-EVT-015",
            ContractType.EVENT,
            "OperationalDatasetUploaded",
            "Record sanitized dataset upload counts",
        ),
        (
            "IC-NETPAY-EVT-016",
            ContractType.EVENT,
            "OperationalDatasetValidated",
            "Record sanitized dataset validation counts",
        ),
        ("IC-NETPAY-EVT-017", ContractType.EVENT, "OperationalDatasetAccepted", "Record accepted dataset counts"),
        ("IC-NETPAY-EVT-018", ContractType.EVENT, "OperationalDatasetRejected", "Record rejected dataset status"),
        (
            "IC-NETPAY-EVT-019",
            ContractType.EVENT,
            "OperationalRowMatchResolved",
            "Record sanitized row-match resolution",
        ),
    )
)

CANONICAL_CONTRACTS += tuple(
    ContractDefinition(
        interaction_contract_id=contract_id,
        version="1.0.0",
        contract_type=contract_type,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="service inbox",
        name=name,
        semantic_purpose=purpose,
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.PLANNED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay service Inbox",
    )
    for contract_id, contract_type, name, purpose in (
        (
            "IC-NETPAY-CMD-009",
            ContractType.COMMAND,
            "CreateNetpayServiceCase",
            "Create a tenant-owned Netpay service case",
        ),
        (
            "IC-NETPAY-CMD-010",
            ContractType.COMMAND,
            "ClassifyAndUpdateNetpayServiceCase",
            "Classify and update a Netpay service case",
        ),
        ("IC-NETPAY-CMD-011", ContractType.COMMAND, "ManageNetpayCaseChecklist", "Manage a Netpay case checklist"),
        ("IC-NETPAY-CMD-012", ContractType.COMMAND, "AssignNetpayServiceCase", "Assign a Netpay service case"),
        ("IC-NETPAY-CMD-013", ContractType.COMMAND, "SetNetpayCaseNextAction", "Set a Netpay case next action"),
        ("IC-NETPAY-CMD-014", ContractType.COMMAND, "TransitionNetpayServiceCase", "Transition a Netpay service case"),
        (
            "IC-NETPAY-CMD-015",
            ContractType.COMMAND,
            "RecordNetpayCaseActivity",
            "Record append-only Netpay case activity",
        ),
        (
            "IC-NETPAY-QRY-005",
            ContractType.QUERY,
            "ListNetpayServiceInbox",
            "List the tenant-scoped Netpay service Inbox",
        ),
        (
            "IC-NETPAY-QRY-006",
            ContractType.QUERY,
            "RetrieveNetpayServiceCaseDetail",
            "Retrieve tenant-scoped Netpay service case detail",
        ),
        ("IC-NETPAY-EVT-003", ContractType.EVENT, "NetpayServiceCaseCreated", "Record Netpay service case creation"),
        (
            "IC-NETPAY-EVT-004",
            ContractType.EVENT,
            "NetpayServiceCaseClassified",
            "Record Netpay service case classification",
        ),
        (
            "IC-NETPAY-EVT-005",
            ContractType.EVENT,
            "NetpayServiceCaseStateChanged",
            "Record Netpay service case state change",
        ),
        (
            "IC-NETPAY-EVT-006",
            ContractType.EVENT,
            "NetpayServiceCaseActivityRecorded",
            "Record Netpay service case activity",
        ),
    )
)

CANONICAL_CONTRACTS += tuple(
    ContractDefinition(
        interaction_contract_id=contract_id,
        version="1.0.0",
        contract_type=contract_type,
        owner_module_id="netpay_merchant_operations",
        owning_context="Netpay Merchant Operations",
        owning_capability="tenant-owned master",
        name=name,
        semantic_purpose=purpose,
        lifecycle=ContractLifecycle.RATIFIED,
        operational_status=ContractOperationalStatus.VERIFIED,
        criticality=ContractCriticality.CORE,
        primary_consumer_or_use_case="Netpay master",
    )
    for contract_id, contract_type, name, purpose in (
        ("IC-NETPAY-CMD-005", ContractType.COMMAND, "CreateNetpayClient", "Create a tenant-owned Netpay Client"),
        (
            "IC-NETPAY-CMD-006",
            ContractType.COMMAND,
            "CreateNetpayCompany",
            "Create a Company under a same-tenant Client",
        ),
        (
            "IC-NETPAY-CMD-007",
            ContractType.COMMAND,
            "CreateNetpayBranch",
            "Create a Branch under a same-tenant Company",
        ),
        (
            "IC-NETPAY-CMD-008",
            ContractType.COMMAND,
            "AssignCorrectOrRemoveNetpayStoreReference",
            "Manage the optional same-Branch Store reference",
        ),
        (
            "IC-NETPAY-QRY-003",
            ContractType.QUERY,
            "ListSearchNetpayMaster",
            "List or search tenant-owned Netpay master records",
        ),
        (
            "IC-NETPAY-QRY-004",
            ContractType.QUERY,
            "RetrieveNetpayMasterDetail",
            "Retrieve tenant-owned Netpay master detail",
        ),
    )
)


def canonical_contracts() -> tuple[ContractDefinition, ...]:
    """Return the immutable, explicit canonical Tier 1 contract baseline."""

    return CANONICAL_CONTRACTS
